openapi: 3.0.3
info:
  title: Fee Calc API
  description: Fee Calc API
  version: 1.0.0
servers:
  - url: http://localhost:8080/
    description: Local development server
paths:
  /calculate-delivery-fee:
    post:
      operationId: calculateFee
      summary: Calculate delivery fee
      description: Calculates the total delivery fee or gives an error message based on the city, vehicle type and weather.
      parameters:
        - $ref: '#/components/parameters/City'
        - $ref: '#/components/parameters/VehicleType'
      responses:
        '200':
          description: Successful operation. Total delivery fee or error message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FeeResponse'
        '400':
          description: Bad request. An error message explaining the issue.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
    FeeResponse:
      type: object
      properties:
        result:
          oneOf:
            - type: number
            - type: string

  parameters:
    City:
      name: city
      in: query
      description: City for fee calculation
      required: true
      schema:
        type: string
        enum:
          - Tallinn
          - Tartu
          - Pärnu
    VehicleType:
      name: vehicleType
      in: query
      description: Vehicle type for fee calculation
      required: true
      schema:
        type: string
        enum:
          - Car
          - Scooter
          - Bike
